// === BookSpritz: Lore System ===

const LoreSystem = {
    init() { this.setupTabSwitching(); this.setupKeywordInputs(); },
    setupTabSwitching() { document.querySelectorAll('.tab-btn').forEach(btn => btn.addEventListener('click', () => { document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active')); document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active')); btn.classList.add('active'); $(btn.dataset.tab + 'Tab').classList.add('active'); })); },
    setupKeywordInputs() { $('addKeywordBtn').addEventListener('click', () => { const ni = $('newKeywordInput'), nn = $('newKeywordNotes'), name = ni.value.trim(); if (name) { getActiveBook().keywords[name] = {notes:nn.value.trim() || "No lore notes yet.", active:true, partialMatch:false, bold:false, italic:false, textColor:''}; ni.value = ''; nn.value = ''; debouncedSave(); this.renderKeywords(); this.highlightKeywords(); } }); },
    renderKeywords() { 
        const list = $('keywordList'); list.innerHTML = ''; const pt = pagesWrapper.innerText.toLowerCase(); 
        const eyeOpen = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>`;
        const eyeClosed = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"/><line x1="1" y1="1" x2="23" y2="23"/></svg>`;
        const trashIcon = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>`;
        Object.keys(getActiveBook().keywords).forEach(name => { 
            const d = getActiveBook().keywords[name]; if (d.partialMatch === undefined) d.partialMatch = false; if (d.bold === undefined) d.bold = false; if (d.italic === undefined) d.italic = false; if (d.textColor === undefined) d.textColor = ''; 
            const sr = d.partialMatch ? new RegExp(this.escapeRegex(name), 'gi') : new RegExp(`\\b${this.escapeRegex(name)}\\b`, 'gi'); const m = pt.match(sr); const c = m ? m.length : 0; 
            const li = document.createElement('li'); li.className = 'keyword-item'; 
            li.innerHTML = `<div class="keyword-main"><span class="keyword-name">${escapeHTML(name)}</span><div class="keyword-actions-bar" style="width:auto;margin:0;"><button class="keyword-icon-btn" data-action="toggle" data-name="${name}">${d.active ? eyeOpen : eyeClosed}</button><button class="keyword-icon-btn" data-action="delete" data-name="${name}">${trashIcon}</button></div></div><div class="keyword-notes">${escapeHTML(d.notes)}</div><div class="keyword-actions-bar"><button class="keyword-action-btn" data-action="edit" data-name="${name}">Edit Lore</button><button class="keyword-action-btn" data-action="replace" data-name="${name}">Replace Word</button><button class="keyword-action-btn" data-action="bake" data-name="${name}">Bake Formats</button><button class="keyword-action-btn ${d.partialMatch ? 'active' : ''}" data-action="toggle-partial" data-name="${name}">${d.partialMatch ? 'Partial' : 'Exact'}</button><span class="keyword-stat">${c} mentions</span></div><div class="keyword-format-bar"><div class="fmt-btn ${d.bold ? 'active' : ''}" data-action="fmt-bold" data-name="${name}" style="font-weight:bold;">B</div><div class="fmt-btn ${d.italic ? 'active' : ''}" data-action="fmt-italic" data-name="${name}" style="font-style:italic;">I</div><input type="color" class="fmt-color" data-action="fmt-color" data-name="${name}" value="${d.textColor || '#4A4A4A'}"></div>`; 
            list.appendChild(li); 
        }); 
        list.querySelectorAll('[data-action="toggle"]').forEach(btn => btn.addEventListener('click', e => { const n = e.currentTarget.dataset.name; getActiveBook().keywords[n].active = !getActiveBook().keywords[n].active; debouncedSave(); this.renderKeywords(); this.highlightKeywords(); })); 
        list.querySelectorAll('[data-action="toggle-partial"]').forEach(btn => btn.addEventListener('click', e => { const n = e.currentTarget.dataset.name; getActiveBook().keywords[n].partialMatch = !getActiveBook().keywords[n].partialMatch; debouncedSave(); this.renderKeywords(); this.highlightKeywords(); })); 
        list.querySelectorAll('[data-action="delete"]').forEach(btn => btn.addEventListener('click', e => { const n = e.currentTarget.dataset.name; CustomUI.confirm(`Delete keyword "${n}"?`, c => { if (c) { delete getActiveBook().keywords[n]; debouncedSave(); this.renderKeywords(); this.highlightKeywords(); } }); })); 
        list.querySelectorAll('[data-action="edit"]').forEach(btn => btn.addEventListener('click', e => { const n = e.currentTarget.dataset.name; CustomUI.prompt(`Edit lore notes for "${n}":`, getActiveBook().keywords[n].notes, nn => { if (nn !== null) { getActiveBook().keywords[n].notes = nn.trim() || "No lore notes yet."; debouncedSave(); this.renderKeywords(); this.highlightKeywords(); } }); })); 
        list.querySelectorAll('[data-action="replace"]').forEach(btn => btn.addEventListener('click', e => this.triggerGlobalReplace(e.currentTarget.dataset.name)));
        list.querySelectorAll('[data-action="bake"]').forEach(btn => btn.addEventListener('click', e => this.triggerBakeFormats(e.currentTarget.dataset.name)));
        list.querySelectorAll('[data-action="fmt-bold"]').forEach(btn => btn.addEventListener('click', e => { const n = e.currentTarget.dataset.name; getActiveBook().keywords[n].bold = !getActiveBook().keywords[n].bold; debouncedSave(); this.renderKeywords(); this.highlightKeywords(); })); 
        list.querySelectorAll('[data-action="fmt-italic"]').forEach(btn => btn.addEventListener('click', e => { const n = e.currentTarget.dataset.name; getActiveBook().keywords[n].italic = !getActiveBook().keywords[n].italic; debouncedSave(); this.renderKeywords(); this.highlightKeywords(); })); 
        list.querySelectorAll('[data-action="fmt-color"]').forEach(inp => inp.addEventListener('input', e => { const n = e.currentTarget.dataset.name; getActiveBook().keywords[n].textColor = e.target.value; debouncedSave(); this.highlightKeywords(); }));
    },
    highlightKeywords() { 
        const sel = window.getSelection(); let marker = null; if (sel.rangeCount > 0 && pagesWrapper.contains(sel.anchorNode)) { const range = sel.getRangeAt(0); marker = document.createElement('span'); marker.id = '__caret_marker__'; range.insertNode(marker); } 
        pagesWrapper.querySelectorAll('span.keyword-span').forEach(el => { const text = document.createTextNode(el.textContent); el.parentNode.replaceChild(text, el); }); pagesWrapper.normalize(); 
        const walker = document.createTreeWalker(pagesWrapper, NodeFilter.SHOW_TEXT, { acceptNode: function(node) { if (!node.nodeValue || node.nodeValue.trim() === '') return NodeFilter.FILTER_REJECT; if (node.parentNode.nodeName === 'MARK' || (node.parentNode.classList && node.parentNode.classList.contains('keyword-span'))) return NodeFilter.FILTER_REJECT; let p = node.parentNode; while (p && p !== pagesWrapper) { if (p.classList && p.classList.contains('canvas-flag')) return NodeFilter.FILTER_REJECT; p = p.parentNode; } return NodeFilter.FILTER_ACCEPT; } }, false); 
        const textNodes = []; let node; while (node = walker.nextNode()) textNodes.push(node); 
        const exactWords = [], partialWords = []; Object.keys(getActiveBook().keywords).forEach(k => { if (getActiveBook().keywords[k].active) { if (getActiveBook().keywords[k].partialMatch) partialWords.push(k); else exactWords.push(k); } }); 
        let patternStr = ''; if (exactWords.length > 0) patternStr += `\\b(${exactWords.map(this.escapeRegex).join('|')})\\b`; if (partialWords.length > 0) { if (patternStr.length > 0) patternStr += '|'; patternStr += `(${partialWords.map(this.escapeRegex).join('|')})`; } 
        if (patternStr !== '') { 
            const regex = new RegExp(patternStr, 'gi'); 
            textNodes.forEach(textNode => { const text = textNode.nodeValue; if (!regex.test(text)) return; regex.lastIndex = 0; let li = 0, m; const frag = document.createDocumentFragment(); let hm = false; while ((m = regex.exec(text)) !== null) { hm = true; frag.appendChild(document.createTextNode(text.substring(li, m.index))); const span = document.createElement('span'); const mn = Object.keys(getActiveBook().keywords).find(k => k.toLowerCase() === m[0].toLowerCase()); const kd = getActiveBook().keywords[mn]; span.className = 'keyword-span'; if (kd) { if (kd.bold) span.style.fontWeight = 'bold'; if (kd.italic) span.style.fontStyle = 'italic'; if (kd.textColor) span.style.color = kd.textColor; span.dataset.notes = kd.notes || ''; } span.textContent = m[0]; frag.appendChild(span); li = regex.lastIndex; } if (hm) { frag.appendChild(document.createTextNode(text.substring(li))); textNode.parentNode.replaceChild(frag, textNode); } }); 
        } 
        if (marker) { const nm = document.getElementById('__caret_marker__'); if (nm) { const nr = document.createRange(); nr.setStartAfter(nm); nr.collapse(true); sel.removeAllRanges(); sel.addRange(nr); nm.remove(); } } 
    },
    getOccurrences(name) { const isPartial = getActiveBook().keywords[name].partialMatch; const wordRegex = isPartial ? new RegExp(this.escapeRegex(name), 'gi') : new RegExp("\\b" + this.escapeRegex(name) + "\\b", 'gi'); const occurrences = []; document.querySelectorAll('#pagesWrapper .page').forEach(pageEl => { const clone = pageEl.cloneNode(true); clone.querySelectorAll('span.keyword-span,mark.find-match,mark.find-active').forEach(m => m.replaceWith(document.createTextNode(m.textContent))); clone.querySelectorAll('.canvas-flag').forEach(f => f.remove()); const walker = document.createTreeWalker(clone, NodeFilter.SHOW_TEXT, { acceptNode: function(node) { if (!node.nodeValue || node.nodeValue.trim() === '') return NodeFilter.FILTER_REJECT; if (node.parentNode.nodeName === 'MARK') return NodeFilter.FILTER_REJECT; return NodeFilter.FILTER_ACCEPT; } }, false); let node; while (node = walker.nextNode()) { const originalText = node.nodeValue; wordRegex.lastIndex = 0; let match; while ((match = wordRegex.exec(originalText)) !== null) { const start = Math.max(0, match.index - 20); const end = Math.min(originalText.length, wordRegex.lastIndex + 20); const context = (start > 0 ? "..." : "") + originalText.substring(start, end).trim() + (end < originalText.length ? "..." : ""); occurrences.push(context); } } }); return occurrences; },
    triggerGlobalReplace(oldName) { CustomUI.prompt(`Replace all instances of "${oldName}" with:`, oldName, newName => { if (!newName || newName === oldName) return; const occurrences = this.getOccurrences(oldName); if (occurrences.length === 0) { CustomUI.alert(`No occurrences of "${oldName}" found.`); return; } this.showReviewModal("Review Global Replacement", "Select instances to replace.", oldName, newName, occurrences, (accepted, oN, nN) => this.applyReplacements(oN, nN, accepted)); }); },
    triggerBakeFormats(name) { const occurrences = this.getOccurrences(name); if (occurrences.length === 0) { CustomUI.alert(`No occurrences of "${name}" found.`); return; } this.showReviewModal("Bake Formats Permanently", "Select instances to bake formatting into the text data.", name, name, occurrences, (accepted, n) => this.applyBake(n, accepted)); },
    showReviewModal(title, msg, oldName, newName, occurrences, callback) { 
        const rl = $('reviewList'); rl.innerHTML = ''; 
        occurrences.forEach((ctx, index) => { const li = document.createElement('li'); li.className = 'history-item review-item'; const isPartial = getActiveBook().keywords[oldName].partialMatch; const rs = isPartial ? this.escapeRegex(oldName) : `\\b${this.escapeRegex(oldName)}\\b`; let safeCtx = ''; { const r = new RegExp(rs, 'gi'); let lastIdx = 0, m2; while ((m2 = r.exec(ctx)) !== null) { safeCtx += escapeHTML(ctx.substring(lastIdx, m2.index)) + '<strong>' + escapeHTML(m2[0]) + '</strong>'; lastIdx = r.lastIndex; } safeCtx += escapeHTML(ctx.substring(lastIdx)); }; li.innerHTML = `<label class="review-label"><input type="checkbox" class="review-checkbox" checked data-index="${index}"><span class="review-text">${safeCtx}</span></label>`; rl.appendChild(li); }); 
        $('reviewModalTitle').innerText = title; $('reviewModal').classList.remove('hidden'); 
        reviewCallback = () => { const cbs = document.querySelectorAll('.review-item .review-checkbox'); const accepted = Array.from(cbs).map(cb => cb.checked); callback(accepted, oldName, newName); }; 
    },
    applyReplacements(oldName, newName, acceptedStatus) { 
        const isPartial = getActiveBook().keywords[oldName].partialMatch; const regex = isPartial ? new RegExp(this.escapeRegex(oldName), 'gi') : new RegExp("\\b" + this.escapeRegex(oldName) + "\\b", 'gi'); let idx = 0; 
        document.querySelectorAll('#pagesWrapper .page').forEach(pageEl => { 
            pageEl.querySelectorAll('span.keyword-span,mark.find-match,mark.find-active').forEach(m => m.replaceWith(document.createTextNode(m.textContent))); pageEl.normalize(); 
            const walker = document.createTreeWalker(pageEl, NodeFilter.SHOW_TEXT, { acceptNode: function(node) { if (!node.nodeValue || node.nodeValue.trim() === '') return NodeFilter.FILTER_REJECT; if (node.parentNode.nodeName === 'MARK') return NodeFilter.FILTER_REJECT; let p = node.parentNode; while (p && p !== pageEl) { if (p.classList && p.classList.contains('canvas-flag')) return NodeFilter.FILTER_REJECT; p = p.parentNode; } return NodeFilter.FILTER_ACCEPT; } }, false); 
            let node; let nodesToUpdate = []; 
            while (node = walker.nextNode()) { const originalText = node.nodeValue; regex.lastIndex = 0; let match; let li = 0; let newText = ''; let hm = false; while ((match = regex.exec(originalText)) !== null) { hm = true; const isAccepted = acceptedStatus[idx]; idx++; newText += originalText.substring(li, match.index); if (isAccepted) newText += (match[0] === match[0].toUpperCase() ? newName.toUpperCase() : newName); else newText += match[0]; li = regex.lastIndex; } if (hm) { newText += originalText.substring(li); nodesToUpdate.push({node, newText}); } } 
            nodesToUpdate.forEach(item => item.node.nodeValue = item.newText); 
        }); 
        const od = getActiveBook().keywords[oldName]; delete getActiveBook().keywords[oldName]; getActiveBook().keywords[newName] = od; saveData(); renderUI(); 
    },
    applyBake(name, acceptedStatus) { 
        const isPartial = getActiveBook().keywords[name].partialMatch; const regex = isPartial ? new RegExp(this.escapeRegex(name), 'gi') : new RegExp("\\b" + this.escapeRegex(name) + "\\b", 'gi'); let idx = 0; const kd = getActiveBook().keywords[name]; 
        let styleStr = ''; if (kd.bold) styleStr += 'font-weight:bold;'; if (kd.italic) styleStr += 'font-style:italic;'; if (kd.textColor) styleStr += `color:${kd.textColor};`; 
        document.querySelectorAll('#pagesWrapper .page').forEach(pageEl => { 
            pageEl.querySelectorAll('span.keyword-span,mark.find-match,mark.find-active').forEach(m => m.replaceWith(document.createTextNode(m.textContent))); pageEl.normalize(); 
            const walker = document.createTreeWalker(pageEl, NodeFilter.SHOW_TEXT, { acceptNode: function(node) { if (!node.nodeValue || node.nodeValue.trim() === '') return NodeFilter.FILTER_REJECT; if (node.parentNode.nodeName === 'MARK') return NodeFilter.FILTER_REJECT; let p = node.parentNode; while (p && p !== pageEl) { if (p.classList && p.classList.contains('canvas-flag')) return NodeFilter.FILTER_REJECT; p = p.parentNode; } return NodeFilter.FILTER_ACCEPT; } }, false); 
            let node; let nodesToUpdate = []; 
            while (node = walker.nextNode()) { const originalText = node.nodeValue; regex.lastIndex = 0; let match; let li = 0; let newHTML = ''; let hm = false; while ((match = regex.exec(originalText)) !== null) { hm = true; const isAccepted = acceptedStatus[idx]; idx++; newHTML += originalText.substring(li, match.index); if (isAccepted && styleStr) newHTML += `<span class="baked-keyword" style="${styleStr}">${match[0]}</span>`; else newHTML += match[0]; li = regex.lastIndex; } if (hm) { newHTML += originalText.substring(li); const temp = document.createElement('div'); temp.innerHTML = newHTML; nodesToUpdate.push({node, parent:node.parentNode, frag:document.createDocumentFragment()}); Array.from(temp.childNodes).forEach(c => nodesToUpdate[nodesToUpdate.length - 1].frag.appendChild(c)); } } 
            nodesToUpdate.forEach(item => item.parent.replaceChild(item.frag, item.node)); 
        }); 
        saveData(); renderUI(); 
    },
    escapeRegex(string) { return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
};
